import {useEffect,useState} from 'react'
import OverviewPage from './OverviewPage'
import RegistryPage from './RegistryPage'
import SmartVisit from './SmartVisit'
import SmartReport from './SmartReport'
import MaternalWorkspace from './MaternalWorkspace'
const api=async p=>(await fetch('/api'+p)).json(),cinus=[['overview','Overview'],['children','Child registry'],['visit','Follow-up visit'],['report','CINUS report']],rh=['clients','anc','labor','postpartum','report']
const readRoute=()=>{const x=location.hash.slice(1);if(x.startsWith('rh/')){const section=x.split('/')[1],merged=section==='delivery'?'labor':section;return['rh',rh.includes(merged)?merged:'clients']}const t=x.replace('cinus/','').split('?')[0];return['cinus',cinus.some(a=>a[0]===t)?t:'overview']}
export default function Shell(){const[[workspace,tab],setRoute]=useState(readRoute()),[children,setChildren]=useState([]),[visits,setVisits]=useState([]),[month,setMonth]=useState('2026-08'),[note,setNote]=useState('');const load=()=>Promise.all([api('/children'),api('/visits')]).then(([c,v])=>{setChildren(c);setVisits(v)});useEffect(()=>{load();const sync=()=>setRoute(readRoute());addEventListener('hashchange',sync);return()=>removeEventListener('hashchange',sync)},[]);const go=(w,t)=>{const next=[w,t];setRoute(next);const hash=`#${w}/${t}`;if(location.hash!==hash)location.hash=hash},done=x=>{setNote(x);load();setTimeout(()=>setNote(''),3500)};const logout=()=>{localStorage.removeItem('clinical-authenticated');location.hash='';location.reload()};const ct={overview:'CINUS child nutrition',children:'Child registry',visit:'Follow-up visit',report:'Official CINUS report'}[tab],rt={clients:'Maternal client & risk classification',anc:'ANC contact schedule',labor:'Labor, delivery and newborn',postpartum:'Postpartum care',report:'Integrated RH card report'}[tab];return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">✚</div><div><strong>KIDANEMIHIRET</strong><span>Integrated clinical system</span></div></div><nav><button className={workspace==='cinus'?'active':''} onClick={()=>go('cinus','overview')}><i>◒</i>CINUS workspace</button><button className={workspace==='rh'?'active':''} onClick={()=>go('rh','clients')}><i>♀</i>Maternal RH care</button></nav><div className="side-footer"><span className="online-dot"/>Kidanemihiret<br/><small>Amhara · Bahir Dar</small><button className="logout-button" onClick={logout}>↪ <span>Log out</span></button></div></aside><main key={workspace}><header><div><p className="eyebrow">KIDANEMIHIRET · AMHARA · BAHIR DAR</p><h1>{workspace==='cinus'?ct:rt}</h1></div></header>{note&&<div className="notice">✓ {note}</div>}{workspace==='cinus'?<><div className="workspace-tabs">{cinus.map(([x,l],i)=><button key={x} className={tab===x?'selected':''} onClick={()=>go('cinus',x)}><span>{i+1}</span>{l}</button>)}</div>{tab==='overview'&&<OverviewPage children={children} visits={visits} go={x=>go('cinus',x)}/>} {tab==='children'&&<RegistryPage children={children} done={done}/>} {tab==='visit'&&<SmartVisit children={children} done={done}/>} {tab==='report'&&<SmartReport month={month} setMonth={setMonth}/>}</>:<MaternalWorkspace section={tab} onSection={x=>go('rh',x)} notify={done}/>}</main></div>}
