import { useEffect, useState } from 'react'
import SmartVisit from './SmartVisit'
import SmartReport from './SmartReport'
const Visit=SmartVisit
const Report=SmartReport
const api=async(p,o)=>{const r=await fetch('/api'+p,o),body=await r.text();let data;try{data=body?JSON.parse(body):null}catch{data=null}if(!r.ok)throw new Error(data?.detail||body||'Request failed');return data}
const monthEnd=m=>{const[y,mo]=m.split('-').map(Number);return `${m}-${String(new Date(y,mo,0).getDate()).padStart(2,'0')}`}
const F=({label,...p})=><label className="field"><span>{label}</span><input {...p}/></label>
const S=({label,options,...p})=><label className="field"><span>{label}</span><select {...p}>{options.map(x=>Array.isArray(x)?<option key={x[0]} value={x[0]}>{x[1]}</option>:<option key={x} value={x}>{x}</option>)}</select></label>
function VisitSearch({children,done}){return null}
export default function App(){const[tab,setTab]=useState('overview'),[children,setChildren]=useState([]),[visits,setVisits]=useState([]),[tally,setTally]=useState(null),[month,setMonth]=useState('2026-08'),[note,setNote]=useState('');const load=async()=>{try{const[c,v,t]=await Promise.all([api('/children'),api('/visits'),api(`/cinus-tally?month=${month}`)]);setChildren(c);setVisits(v);setTally(t)}catch{setNote('Unable to connect to clinic server.')}};useEffect(()=>{load()},[month]);const done=x=>{setNote(x);load();setTimeout(()=>setNote(''),3500)};const tabs=[['overview','Overview'],['children','Child registry'],['visit','Follow-up visit'],['report','CINUS report']];const heading={overview:'CINUS child nutrition',children:'Child registry',visit:'Follow-up visit',report:'Official CINUS report'}[tab];return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">✚</div><div><strong>CINUS</strong><span>Child nutrition system</span></div></div><nav><button className="active"><i>◒</i>CINUS workspace</button></nav><div className="side-footer"><span className="online-dot"/>Facility workspace<br/><small>MoH CINUS reporting</small></div></aside><main><header><div><p className="eyebrow">ADDIS CLINIC · BOLE</p><h1>{heading}</h1></div></header><div className="workspace-tabs" role="tablist">{tabs.map(([id,label],index)=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'selected':''} onClick={()=>setTab(id)}><span>{index+1}</span>{label}</button>)}</div>{note&&<div className="notice">✓ {note}</div>}{tab==='overview'&&<Overview tally={tally} children={children} visits={visits} go={setTab}/>} {tab==='children'&&<Children children={children} done={done}/>} {tab==='visit'&&<Visit children={children} done={done}/>} {tab==='report'&&<Report tally={tally} month={month} setMonth={setMonth} visits={visits}/>}</main></div>}
function Overview({tally,children,visits,go}){const s=tally?.tally.screen;const n=s?Object.values(s).reduce((a,x)=>a+x.normal,0):0,m=s?Object.values(s).reduce((a,x)=>a+x.mam+x.sam,0):0;return <><section className="hero"><div><p>One record, every report</p><h2>Capture a child visit once. Generate CINUS automatically.</h2><button className="primary" onClick={()=>go('visit')}>Record follow-up visit <span>→</span></button></div><div className="hero-graphic"><div>✚</div><p>Child-centred<br/>care data</p></div></section><section className="metrics"><Metric n={children.length} l="Registered children" t="blue"/><Metric n={visits.length} l="Follow-up visits" t="yellow"/><Metric n={n} l="Normal screened" t="green"/><Metric n={m} l="MAM / SAM cases" t="purple"/></section><section className="split"><div className="panel"><p className="eyebrow">DATA FLOW</p><h3>Primary records first</h3><p className="helper">Child registration → visit → growth assessment → screening and services → automatic CINUS PDF.</p><button className="secondary" onClick={()=>go('children')}>Register a child</button></div><div className="panel report-callout"><p className="eyebrow">MONTHLY REPORT</p><h3>{tally?.records||0} visits included</h3><div className="progress"><span/></div><p>Tally totals are generated from saved child visits only.</p><button className="secondary" onClick={()=>go('report')}>Open report</button></div></section></>};function Metric({n,l,t}){return <div className={`metric ${t}`}><div className="metric-icon">{t==='blue'?'♙':t==='yellow'?'♡':t==='green'?'◒':'!'}</div><div><b>{n}</b><span>{l}</span></div></div>}
function Children({children,done}){const[f,setF]=useState({first_name:'',last_name:'',sex:'Female',date_of_birth:'',mother_name:'',phone:'',region:'Addis Ababa',woreda:'Bole',kebele:'',household_id:''});const u=e=>setF({...f,[e.target.name]:e.target.value});const save=async e=>{e.preventDefault();try{await api('/children',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});done('Child registration saved.')}catch(x){alert(x.message)}};return <div className="two-column"><form className="panel form-card" onSubmit={save}><p className="eyebrow">NEW CHILD</p><h3>Child registration</h3><div className="form-grid"><F label="First name" name="first_name" value={f.first_name} onChange={u} required/><F label="Last name" name="last_name" value={f.last_name} onChange={u} required/><S label="Sex" name="sex" value={f.sex} onChange={u} options={['Female','Male']}/><F label="Date of birth" type="date" name="date_of_birth" value={f.date_of_birth} onChange={u} required/><F label="Mother / caregiver" name="mother_name" value={f.mother_name} onChange={u}/><F label="Phone" name="phone" value={f.phone} onChange={u}/><F label="Woreda" name="woreda" value={f.woreda} onChange={u}/><F label="Kebele" name="kebele" value={f.kebele} onChange={u}/><F label="Household ID" name="household_id" value={f.household_id} onChange={u}/></div><button className="primary">Save child record <span>→</span></button></form><section className="panel"><p className="eyebrow">REGISTRY</p><h3>{children.length} child profiles</h3><div className="patient-list">{children.map(c=><div className="patient-row" key={c.id}><div className="avatar">{c.first_name[0]}{c.last_name[0]}</div><div><b>{c.first_name} {c.last_name}</b><small>{c.child_code} · {c.sex}</small></div><span>{c.woreda}</span></div>)}</div></section></div>}
function VisitLegacy({children,done}){
 const[f,setF]=useState({child_id:'',visit_date:'2026-08-25',weight:'',height:'',muac:'',edema:false,health_worker:'Clinical Officer',nutrition_result:'normal',referral:'',vitamin_a_dose:'0',deworming_dose:'0',developmental_result:'ndd',development_notes:''});
 const[scores,setScores]=useState(null),[scoreState,setScoreState]=useState('Select a child, then enter visit date, weight and length/height.');
 const u=e=>setF({...f,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value});
 useEffect(()=>{if(f.edema&&f.nutrition_result!=='sam')setF(x=>({...x,nutrition_result:'sam'}))},[f.edema]);
 const child=children.find(x=>x.id===+f.child_id), age=child&&f.visit_date?Math.max(0,(new Date(f.visit_date).getFullYear()-new Date(child.date_of_birth).getFullYear())*12+new Date(f.visit_date).getMonth()-new Date(child.date_of_birth).getMonth()-(new Date(f.visit_date).getDate()<new Date(child.date_of_birth).getDate()?1:0)):null;
 useEffect(()=>{if(!f.child_id||!f.visit_date||!f.weight||!f.height){setScores(null);setScoreState('Select a child, then enter visit date, weight and length/height.');return}setScoreState('Calculating WHO growth scores...');const timer=setTimeout(()=>api(`/growth-assessment?child_id=${f.child_id}&visit_date=${f.visit_date}&weight=${f.weight}&height=${f.height}`).then(x=>{setScores(x);setScoreState('WHO growth scores calculated automatically.');}).catch(x=>{setScores(null);setScoreState(`Unable to calculate: ${x.message}`)}),250);return()=>clearTimeout(timer)},[f.child_id,f.visit_date,f.weight,f.height]);
 const save=async e=>{e.preventDefault();try{const b={...f,child_id:+f.child_id,weight:+f.weight,height:+f.height,muac:+f.muac,vitamin_a_dose:+f.vitamin_a_dose,deworming_dose:+f.deworming_dose};await api('/visits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});done('Complete child visit saved with WHO growth scores and added to CINUS tally.')}catch(x){setScoreState(`Cannot save this visit: ${x.message}`)}};
 return <form className="panel form-card wide-form" onSubmit={save}><p className="eyebrow">ONE VISIT, LINKED RECORDS</p><h3>Growth, nutrition and services</h3><div className="form-grid cols-3"><S label="Registered child" name="child_id" value={f.child_id} onChange={u} options={[['','Select child'],...children.map(c=>[c.id,`${c.first_name} ${c.last_name} · ${c.child_code}`])]} required/><F label="Visit date" type="date" name="visit_date" value={f.visit_date} onChange={u}/><F label="Health worker" name="health_worker" value={f.health_worker} onChange={u}/><F label="Weight (kg)" type="number" step="0.1" name="weight" value={f.weight} onChange={u} required/><F label="Length / height (cm)" type="number" step="0.1" name="height" value={f.height} onChange={u} required/><F label="MUAC (cm)" type="number" step="0.1" name="muac" value={f.muac} onChange={u} required/></div><div className="section-title">Automatic WHO growth assessment</div><div className="form-grid cols-3"><F label="WAZ — underweight" type="number" value={scores?.waz??''} readOnly/><F label="HAZ — stunting" type="number" value={scores?.haz??''} readOnly/><F label="WHZ — wasting" type="number" value={scores?.whz??''} readOnly/></div><p className="helper">{scoreState}</p><p className="helper">Calculated from sex, date of birth, visit date, weight and length/height using WHO child growth standards. These values cannot be edited manually.</p><div className="checks"><p>Services delivered {age!==null&&<small>· Child age: {age} months</small>}</p><div><label><input type="checkbox" name="edema" checked={f.edema} onChange={u}/><span>Oedema present</span></label><S label="Vitamin A dose" name="vitamin_a_dose" value={f.vitamin_a_dose} onChange={u} disabled={age===null||age<6||age>59} options={[[0,age===null?'Select child first':age<6||age>59?'Not eligible (6–59 months)':'No Vitamin A given'],[1,'Dose 1 given'],[2,'Dose 2 given']]}/><S label="Deworming dose" name="deworming_dose" value={f.deworming_dose} onChange={u} disabled={age===null||age<24||age>59} options={[[0,age===null?'Select child first':age<24||age>59?'Not eligible (24–59 months)':'No deworming given'],[1,'Dose 1 given'],[2,'Dose 2 given']]}/></div></div><div className="form-grid cols-3"><S label="Nutrition screening" name="nutrition_result" value={f.nutrition_result} onChange={u} options={['normal','mam','sam']}/><S label="Development result" name="developmental_result" value={f.developmental_result} onChange={u} options={['ndd','sdd','cdd']}/><F label="Referral / action" name="referral" value={f.referral} onChange={u}/></div><button className="primary">Save complete child visit <span>→</span></button></form>}
function ReportLegacy(){return null}
