import {useState} from 'react'
const F=({label,...p})=><label className="field"><span>{label}</span><input {...p}/></label>
const choices={
 'Mode of delivery':['SVD','C/Section','Vacuum/Forceps','Episiotomy'],
 'AMTSL uterotonic':['Oxytocin','Ergometrine','Misoprostol'],
 'Placenta':['CCT','Complete','Incomplete','MRP'],
 'Tear repair':['1st degree','2nd degree','3rd degree'],
 'Newborn':['Single','Multiple','Alive'],
 'Stillbirth':['Macerated','Fresh'],
 'Sex':['Male','Female'],
 'Maturity':['Term','Preterm'],
 'Newborn care':['HBV birth dose','Vitamin K','TTC','Skin-to-skin contact'],
 'Obstetric complication action':['Managed','Referred'],
 'Complications':['Eclampsia','PPH','APH','PROM/Sepsis','Ruptured uterus','Repaired','Hysterectomy','Obstructed/prolonged labor'],
 'HIV testing accepted':['Yes','No'],
 'HIV test result':['Positive','Negative']
}
const deliveryFields=[['Delivery date','delivery_date','date'],['Delivery time','delivery_time','time'],['Apgar score','apgar'],['Birth weight (g)','birth_weight','number'],['Length (cm)','length','number'],['BCG date','bcg_date','date'],['OPV 0 date','opv0_date','date'],['Feeding option - EBF','feeding_ebf'],['Feeding option - ERF','feeding_erf'],['ARV treatment for mother (type)','arv_mother'],['ARV prophylaxis for newborn (type)','arv_newborn'],['Remark','remark'],['Delivered by','delivered_by'],['Signature','signature']]
const postpartumRows=['Date','BP','PR / RR','Temperature','Uterus contracted / PPH assessment','Dribbling / leaking urine','Anemia','Vaginal discharge after 4 weeks','Pelvic examination if indicated','Breast examination','IFA supplementation','Danger signs, FP, hygiene, nutrition, EPI, ITN and breastfeeding counselling','Baby breathing','Baby breastfeeding','Baby weight (g)','Immunization','HIV tested','HIV test result','ARV treatment for mother (type)','ARV prophylaxis for newborn (type)','Feeding option EBF / RF','Newborn referred to chronic HIV infant care','Family planning counselled / method provided','Action taken','Remark']
const periods=[['24 hours','24 hrs stay'],['25-48 hours','25-48 hrs'],['49-72 hours','49-72 hrs'],['73 hours-7 days','73 hrs-7 days'],['8-42 days','8-42 days']]
export default function DeliveryPostpartum({mode,f,patch,save}){return mode==='delivery'?<Delivery f={f} patch={patch} save={save}/>:<Postpartum f={f} patch={patch} save={save}/>}
function Delivery({f,patch,save}){const data=f.sections.delivery||{},read=key=>data[key]??({'delivery_date':'Delivery date','delivery_time':'Delivery time','apgar':'Apgar score','birth_weight':'Birth weight (g)','length':'Length (cm)','bcg_date':'BCG date','opv0_date':'OPV 0 date','delivered_by':'Delivered by'}[key]||key),list=value=>Array.isArray(value)?value:value?[value]:[],choiceGroups=Object.entries(choices),[activeChoice,setActiveChoice]=useState(choiceGroups[0][0]),set=(k,v)=>patch('delivery',k,v),toggle=(group,item)=>{const current=list(data[group]);set(group,current.includes(item)?current.filter(x=>x!==item):[...current,item])};const selected=choiceGroups.find(([group])=>group===activeChoice)||choiceGroups[0],complete=Object.values(data).filter(x=>Array.isArray(x)?x.length:String(x||'').trim()).length;return <section className="panel form-card delivery-page compact-delivery"><div className="panel-heading"><div><p className="eyebrow">PAGE 4 · DELIVERY SUMMARY</p><h3>Delivery, newborn and immediate care</h3><p className="helper">Select every intervention or outcome that applies, then enter the measured values.</p></div><span className="tag">{complete} groups recorded</span></div><div className="delivery-snapshot"><article><span>Mode</span><b>{list(data['Mode of delivery']).join(', ')||'-'}</b></article><article><span>Newborn</span><b>{list(data.Newborn||data['Newborn number']||data['Newborn status']).join(', ')||'-'}</b></article><article><span>Sex</span><b>{list(data.Sex).join(', ')||'-'}</b></article><article><span>Weight</span><b>{read('birth_weight')||'-'} g</b></article></div><div className="form-grid cols-4 compact-grid">{deliveryFields.slice(0,7).map(([l,k,t])=><F key={k} label={l} type={t} value={read(k)||''} onChange={e=>set(k,e.target.value)}/>)}</div><div className="delivery-choice-shell"><div className="compact-stepper delivery-stepper">{choiceGroups.map(([group,items])=><button key={group} className={activeChoice===group?'active':''} onClick={()=>setActiveChoice(group)}><span>{group}</span><small>{list(data[group]).length}/{items.length}</small></button>)}</div><section className="delivery-choice active-choice"><h4>{selected[0]}</h4><div>{selected[1].map(item=><label className={list(data[selected[0]]).includes(item)?'selected':''} key={item}><input type="checkbox" checked={list(data[selected[0]]).includes(item)} onChange={()=>toggle(selected[0],item)}/><span>{item}</span></label>)}</div></section></div><section className="anc-care-group compact-provider"><h4>Treatment, feeding and provider</h4><div className="form-grid cols-4">{deliveryFields.slice(7).map(([l,k,t])=><F key={k} label={l} type={t} value={read(k)||''} onChange={e=>set(k,e.target.value)}/>)}</div></section><button className="primary" onClick={save}>Save delivery and newborn summary</button></section>}
function Postpartum({f,patch,save}){const data=f.sections.postpartum||{},has=p=>postpartumRows.some(row=>String(data[p+row]||'').trim()),recorded=periods.filter(([p])=>has(p)),[active,setActive]=useState(recorded.length?recorded[recorded.length-1][0]:periods[0][0]);const set=(row,value)=>patch('postpartum',active+row,value),meta=periods.find(([p])=>p===active);return <section className="panel form-card postpartum-page"><div className="panel-heading"><div><p className="eyebrow">PAGE 4 · IV. POSTPARTUM CARE</p><h3>Mother and newborn follow-up</h3><p className="helper">Record the complete maternal and newborn assessment at each follow-up period.</p></div><span className="tag">{recorded.length} of 5 periods recorded</span></div><div className="contact-nav postpartum-nav">{periods.map(([p,label],i)=><button key={p} className={`${active===p?'active':''} ${has(p)?'complete':''}`} onClick={()=>setActive(p)}><span>{has(p)?'✓':i+1}</span><b>{label}</b><small>{has(p)?'Recorded':'Not recorded'}</small></button>)}</div><div className="active-contact-head"><div><p className="eyebrow">SELECTED FOLLOW-UP</p><h3>{meta[1]}</h3></div><span>{postpartumRows.filter(row=>String(data[active+row]||'').trim()).length} of {postpartumRows.length} fields</span></div><section className="anc-care-group"><h4>Maternal and newborn assessment</h4><div className="form-grid cols-3">{postpartumRows.map(row=><F key={row} label={row} type={row==='Date'?'date':'text'} value={data[active+row]||''} onChange={e=>set(row,e.target.value)}/>)}</div></section><div className="anc-savebar"><button className="primary" onClick={save}>Save {meta[1]} assessment</button>{periods.findIndex(([p])=>p===active)<4&&<button className="secondary" onClick={()=>setActive(periods[periods.findIndex(([p])=>p===active)+1][0])}>Next period →</button>}</div></section>}
