import {useEffect,useState} from 'react'

const clock=()=>new Date().toTimeString().slice(0,5)
const fresh=()=>({time:clock(),hour:'',fhr:'140',amniotic_fluid:'Clear',moulding:'0',cervix:'',descent:'',contractions:'3',contraction_duration:'40',oxytocin_ul:'',drops_min:'',drugs_fluids:'',pulse:'80',systolic:'120',diastolic:'80',temperature:'36.8',urine_protein:'Negative',urine_acetone:'Negative',urine_volume:''})
const Field=({label,...props})=><label className="field"><span>{label}</span><input {...props}/></label>
const Group=({title,children})=><section className="anc-care-group"><h4>{title}</h4><div className="form-grid cols-4">{children}</div></section>
const alertItems=o=>[
 +o.fhr&&(+o.fhr<110||+o.fhr>160)?`FHR ${o.fhr} bpm`:'',
 o.amniotic_fluid&&/meconium|blood|m|b/i.test(o.amniotic_fluid)?`Amniotic fluid ${o.amniotic_fluid}`:'',
 o.moulding&&/\+\+/.test(o.moulding)?`Moulding ${o.moulding}`:'',
 +o.systolic>=140||+o.diastolic>=90?`BP ${o.systolic||'-'}/${o.diastolic||'-'}`:'',
 +o.temperature>=38?`Temperature ${o.temperature} C`:'',
 +o.contractions>5?`${o.contractions} contractions / 10 min`:'',
 o.urine_protein&&/positive|\+|p\+/i.test(o.urine_protein)?`Urine protein ${o.urine_protein}`:'',
 o.urine_acetone&&/positive|\+|a\+/i.test(o.urine_acetone)?`Urine acetone ${o.urine_acetone}`:''
].filter(Boolean)

export default function Partograph({f,patch,save,onDelivery,cycleAction}){
 const labor=f.sections.labor||{}, observations=Array.isArray(labor.observations)?labor.observations:[]
 const locked=f.care_status==='closed'||!!f.sections._meta?.labor_submitted
 const[o,setO]=useState(fresh),[editing,setEditing]=useState(observations.length?observations.length-1:null),[message,setMessage]=useState(''),[now,setNow]=useState(clock()),[activeGroup,setActiveGroup]=useState('fetal'),[task,setTask]=useState('observation'),[chartIndex,setChartIndex]=useState(0)
 useEffect(()=>{const timer=setInterval(()=>setNow(clock()),1000);return()=>clearInterval(timer)},[])
 useEffect(()=>{const timer=setInterval(()=>setChartIndex(i=>(i+1)%3),5000);return()=>clearInterval(timer)},[])
 const update=e=>locked?setMessage('Labor partograph is submitted and now view only.'):setO(x=>({...x,[e.target.name]:e.target.value})),header=(key,value)=>locked?setMessage('Labor admission is submitted and now view only.'):patch('labor',key,value)
 const today=new Date().toISOString().slice(0,10), admissionDate=labor.admission_date||today, admissionTime=labor.admission_time||clock()
 const elapsed=()=>{const start=new Date(`${admissionDate}T${admissionTime}`),seen=new Date(`${admissionDate}T${o.time}`);if(seen<start)seen.setDate(seen.getDate()+1);return Math.max(0,(seen-start)/3600000).toFixed(1)}
 const persist=async next=>{if(locked){setMessage('Labor partograph is submitted and now view only.');return}const nextLabor={...labor,admission_date:admissionDate,admission_time:admissionTime,observations:next};patch('labor','admission_date',admissionDate);patch('labor','admission_time',admissionTime);patch('labor','observations',next);await save({...f,sections:{...f.sections,labor:nextLabor}})}
 const add=async()=>{if(locked){setMessage('Labor partograph is submitted and now view only.');return}if(!o.time){setMessage('Enter the observation time.');return}const isNew=editing===null,entry={...o,hour:o.hour||elapsed(),alerts:alertItems(o)};const next=[...observations];isNew?next.push(entry):next.splice(editing,1,entry);next.sort((a,b)=>(a.time||'').localeCompare(b.time||''));await persist(next);if(isNew){setO(fresh());setEditing(null);setActiveGroup('fetal');setTask('observation');setMessage(entry.alerts.length?'Observation saved. Alert values need assessment and plan.':'Observation saved. Ready for next observation.')}else{const savedIndex=next.findIndex(x=>x.time===entry.time);setO(entry);setEditing(savedIndex);setTask('observation');setMessage('Observation updated and saved.')}}
 const edit=index=>{if(locked){setMessage('Labor partograph is submitted and now view only.');return}setO(observations[index]);setEditing(index);document.querySelector('.partograph-entry')?.scrollIntoView({behavior:'smooth'})}
 const remove=async index=>{if(locked){setMessage('Labor partograph is submitted and now view only.');return}await persist(observations.filter((_,i)=>i!==index));setMessage('Observation removed and record updated.')}
 const groups=[
  ['time','Time column',<><Field label="Time" type="time" name="time" value={o.time} onChange={update}/><Field label="Hours since admission" type="number" step="0.5" name="hour" value={o.hour} onChange={update}/></>],
  ['fetal','Fetal condition',<><Field label="Fetal heart rate (bpm)" type="number" min="80" max="200" name="fhr" value={o.fhr} onChange={update}/><Field label="Amniotic fluid" name="amniotic_fluid" placeholder="I / C / M / B" value={o.amniotic_fluid} onChange={update}/><Field label="Moulding" name="moulding" placeholder="0 / + / ++ / +++" value={o.moulding} onChange={update}/></>],
  ['progress','Labor progress',<><Field label="Cervix (cm) - plot X" type="number" min="0" max="10" step="0.5" name="cervix" value={o.cervix} onChange={update}/><Field label="Descent of head - plot O" type="number" min="0" max="5" name="descent" value={o.descent} onChange={update}/><Field label="Contractions per 10 minutes" type="number" min="0" max="5" name="contractions" value={o.contractions} onChange={update}/><Field label="Contraction duration (seconds)" type="number" name="contraction_duration" value={o.contraction_duration} onChange={update}/></>],
  ['treatment','Oxytocin and fluids',<><Field label="Oxytocin U/L" name="oxytocin_ul" value={o.oxytocin_ul} onChange={update}/><Field label="Drops/min" type="number" name="drops_min" value={o.drops_min} onChange={update}/><Field label="Drugs given and IV fluids" name="drugs_fluids" value={o.drugs_fluids} onChange={update}/></>],
  ['maternal','Maternal condition',<><Field label="Pulse (bpm)" type="number" name="pulse" value={o.pulse} onChange={update}/><Field label="Systolic BP" type="number" name="systolic" value={o.systolic} onChange={update}/><Field label="Diastolic BP" type="number" name="diastolic" value={o.diastolic} onChange={update}/><Field label="Temperature C" type="number" step="0.1" name="temperature" value={o.temperature} onChange={update}/></>],
  ['urine','Urine',<><Field label="Protein" name="urine_protein" value={o.urine_protein} onChange={update}/><Field label="Acetone" name="urine_acetone" value={o.urine_acetone} onChange={update}/><Field label="Volume (mL)" type="number" name="urine_volume" value={o.urine_volume} onChange={update}/></>]
 ]
 const active=groups.find(([id])=>id===activeGroup)||groups[0],filled=Object.values(o).filter(v=>String(v||'').trim()).length,alerts=alertItems(o)
 const charts=[['fhr','Fetal heart rate',[['fhr','#157078',80,200]]],['labor','Cervix and head descent',[['cervix','#c34f4f',0,10],['descent','#276aa5',0,10]]],['mother','Pulse and blood pressure',[['pulse','#7547a8',60,180],['systolic','#c34f4f',60,180],['diastolic','#276aa5',60,180]]]]
 const actionFields=[['Assessment / deviation noted','assessment'],['Plan / action agreed','plan'],['Supportive care given','supportive_care'],['Provider initials','initials']]
 const actionValue=k=>labor[k]||({assessment:alerts.length?alerts.join('; '):'Normal labor progress and wellbeing',plan:alerts.length?'Senior review / appropriate action':'Continue routine monitoring',supportive_care:'Companion, fluids, mobility and pain relief supported',initials:'Provider'}[k]||'')
 const saveAction=()=>{if(locked){setMessage('Labor partograph is submitted and now view only.');return}const nextLabor={...labor};actionFields.forEach(([,k])=>{if(!String(nextLabor[k]||'').trim())nextLabor[k]=actionValue(k)});save({...f,sections:{...f.sections,labor:nextLabor}})}
 const saveAdmission=async()=>{if(locked){onDelivery?.();return}const nextMeta={...(f.sections._meta||{}),labor_submitted:true};await save({...f,sections:{...f.sections,labor:{...labor,admission_date:admissionDate,admission_time:admissionTime,ruptured_membranes:labor.ruptured_membranes||'Intact'},_meta:nextMeta}});onDelivery?.()}
 return <section className={`panel form-card partograph compact-labor ${locked?'stage-locked':''}`}><div className="panel-heading compact-head"><div><p className="eyebrow">PAGE 3 · INTRAPARTUM CARE</p><h3>Labor partograph</h3></div><div className="inline-actions">{cycleAction}<span className="tag">{observations.length} observations</span>{locked&&<span className="tag locked-tag">View only</span>}</div></div>
  <div className="labor-two-column"><div className="labor-record-col"><div className="labor-task-tabs"><button className={task==='observation'?'active':''} onClick={()=>setTask('observation')}>Observation</button><button className={task==='action'?'active':''} onClick={()=>setTask('action')}>Assessment & plan</button></div><div className="form-grid cols-4 compact-grid compact-admission"><Field label="Admission date" type="date" value={admissionDate} onChange={e=>header('admission_date',e.target.value)}/><Field label="Admission time" type="time" value={admissionTime} onChange={e=>header('admission_time',e.target.value)}/><Field label="Membranes" placeholder="Intact / ruptured" value={labor.ruptured_membranes||'Intact'} onChange={e=>header('ruptured_membranes',e.target.value)}/><Field label="Hours ruptured" type="number" value={labor.ruptured_hours||''} onChange={e=>header('ruptured_hours',e.target.value)}/></div>
   {task==='observation'?<div className="partograph-entry compact-entry"><div className="active-contact-head compact-head"><div><p className="eyebrow">{editing===null?'NEW OBSERVATION':'EDIT OBSERVATION'}</p><h3>{editing===null?'Record values':`Observation ${editing+1}`}</h3></div>{message&&<span>{message}</span>}</div>
    {alerts.length>0&&<div className="labor-alert-list">{alerts.map(x=><span key={x}>{x}</span>)}</div>}
    <div className="anc-detail-shell labor-entry-shell"><nav className="anc-detail-nav">{groups.map(([id,title])=><button key={id} className={activeGroup===id?'active':''} onClick={()=>setActiveGroup(id)}><span>{title}</span></button>)}</nav><Group title={active[1]}>{active[2]}</Group></div>
    <div className="partograph-actions"><button className="secondary" disabled={locked} onClick={add}>{editing===null?'Record observation':'Update observation'}</button>{editing!==null&&observations.length>1&&<button className="link" disabled={locked} onClick={()=>{setEditing(null);setO(fresh())}}>Cancel edit</button>}</div>
   </div>:<section className="anc-care-group compact-action-plan"><h4>Assessment, response and next action</h4><div className="form-grid cols-4">{actionFields.map(([l,k])=><Field key={k} label={l} value={actionValue(k)} onChange={e=>header(k,e.target.value)}/>)}</div><button className="primary" disabled={locked} onClick={saveAction}>Save assessment and plan</button></section>}<button className="primary" disabled={locked} onClick={saveAdmission}>{locked?'Admission submitted - open delivery from tabs':'Save admission details and open delivery'}</button></div>
   <div className="labor-visual-col"><div className="partograph-clock compact-clock"><span className="online-dot"/><b>{now}</b><small>Admission {admissionDate} · {admissionTime}</small></div><div className="labor-summary compact-labor-summary"><article><span>Latest FHR</span><b>{observations.at(-1)?.fhr||o.fhr||'-'}</b><small>bpm</small></article><article><span>Cervix</span><b>{observations.at(-1)?.cervix||o.cervix||'-'}</b><small>cm</small></article><article><span>BP</span><b>{observations.at(-1)?.systolic||o.systolic||'-'}/{observations.at(-1)?.diastolic||o.diastolic||'-'}</b><small>mmHg</small></article><article><span>Entry</span><b>{filled}</b><small>fields</small></article></div>
    <div className="partograph-slider"><div className="chart-tabs">{charts.map(([,title],i)=><button key={title} className={chartIndex===i?'active':''} onClick={()=>setChartIndex(i)}>{title}</button>)}</div><Chart type={charts[chartIndex][0]} title={charts[chartIndex][1]} data={observations} lines={charts[chartIndex][2]}/></div>
    <div className="table-scroll partograph-history compact-history"><table><thead><tr><th>Time</th><th>Baby</th><th>Labor</th><th>Mother</th><th>Urine / Rx</th><th></th></tr></thead><tbody>{observations.length?observations.map((x,i)=><tr key={i}><td><b>{x.time}</b><small>{x.hour||'-'}h</small></td><td>{x.fhr||'-'} bpm<small>{x.amniotic_fluid||'-'} · M {x.moulding||'-'}</small></td><td>{x.cervix||'-'} cm · D {x.descent||'-'}<small>{x.contractions||'-'}/10m · {x.contraction_duration||'-'}s</small></td><td>{x.systolic||'-'}/{x.diastolic||'-'}<small>P {x.pulse||'-'} · T {x.temperature||'-'}</small></td><td>P {x.urine_protein||'-'} · A {x.urine_acetone||'-'}<small>{x.oxytocin_ul||'-'} · {x.drops_min||'-'} d/m</small></td><td><button className="link" disabled={locked} onClick={()=>edit(i)}>Edit</button><button className="link danger-link" disabled={locked} onClick={()=>remove(i)}>Remove</button></td></tr>):<tr><td colSpan="6" className="empty-table">No labor observations recorded.</td></tr>}</tbody></table></div></div></div>
 </section>
}

function Chart({type,title,data,lines}){const w=640,h=250,left=58,top=16,cols=24,rows=type==='labor'?10:12,cell=22,plotW=cols*cell,plotH=rows*14,bottom=top+plotH,hours=Array.from({length:13},(_,i)=>i),yTicks=type==='labor'?Array.from({length:11},(_,i)=>10-i):type==='fhr'?Array.from({length:13},(_,i)=>200-i*10):Array.from({length:13},(_,i)=>180-i*10),range=type==='labor'?[0,10]:type==='fhr'?[80,200]:[60,180],xFor=(d,i)=>left+((Number.isFinite(+d.hour)?+d.hour:i)/(type==='labor'?12:12))*plotW,yFor=v=>bottom-((+v-range[0])/(range[1]-range[0]))*plotH,points=(key)=>data.map((d,i)=>{if(d[key]===''||!Number.isFinite(+d[key]))return null;return `${Math.max(left,Math.min(left+plotW,xFor(d,i)))},${Math.max(top,Math.min(bottom,yFor(d[key])))}`}).filter(Boolean).join(' '),guide=(startHour,label)=>{const x1=left+(startHour/12)*plotW,y1=yFor(4),x2=left+((startHour+6)/12)*plotW,y2=yFor(10),tx=(x1+x2)/2-18,ty=(y1+y2)/2-6;return <g key={label}><line className="guide-line" x1={x1} y1={y1} x2={x2} y2={y2}/><text className="guide-label" x={tx} y={ty} transform={`rotate(-28 ${tx} ${ty})`}>{label}</text></g>};return <article className={`paper-chart ${type}`}><b>{title}</b><svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none"><text className="axis-title" x="8" y={top+plotH/2}>{type==='fhr'?'Fetal Heart rate':type==='labor'?'Cervix (cm) plot X':'Pulse / BP'}</text>{yTicks.map((v,i)=><g key={v}><text className="axis-num" x={left-8} y={top+i*(plotH/rows)+4}>{v}</text><line className={i%4===0?'major-grid':'grid'} x1={left} x2={left+plotW} y1={top+i*(plotH/rows)} y2={top+i*(plotH/rows)}/></g>)}{Array.from({length:cols+1},(_,i)=><line key={i} className={i%2===0?'major-grid':'grid'} y1={top} y2={bottom+30} x1={left+i*cell} x2={left+i*cell}/>)}{type==='labor'&&[guide(0,'Alert'),guide(4,'Action')]}{lines.map(([key,color])=><polyline key={key} points={points(key)} fill="none" stroke={color} strokeWidth="3"/>)}{lines.map(([key,color])=>data.map((d,i)=>d[key]!==''&&Number.isFinite(+d[key])?<circle key={key+i} cx={Math.max(left,Math.min(left+plotW,xFor(d,i)))} cy={Math.max(top,Math.min(bottom,yFor(d[key])))} r="3.5" fill="#fff" stroke={color} strokeWidth="2"/>:null))}<line className="major-grid" x1={left} x2={left+plotW} y1={bottom} y2={bottom}/><text className="axis-num hour-label" x={left-38} y={bottom+19}>Hour</text><text className="axis-num hour-label" x={left-38} y={bottom+36}>Time</text>{hours.map(i=><text key={i} className="axis-num hour-num" x={left+i*cell*2-3} y={bottom+19}>{i}</text>)}</svg><div className="chart-legend">{lines.map(([key,color])=><span key={key}><i style={{background:color}}/>{key.replace('_',' ')}</span>)}</div></article>}
