import {useEffect,useState} from 'react'

const clock=()=>new Date().toTimeString().slice(0,5)
const fresh=()=>({time:clock(),hour:'',fhr:'',amniotic_fluid:'',moulding:'',cervix:'',descent:'',contractions:'',contraction_duration:'',oxytocin_ul:'',drops_min:'',drugs_fluids:'',pulse:'',systolic:'',diastolic:'',temperature:'',urine_protein:'',urine_acetone:'',urine_volume:''})
const Field=({label,...props})=><label className="field"><span>{label}</span><input {...props}/></label>
const Group=({title,children})=><section className="anc-care-group"><h4>{title}</h4><div className="form-grid cols-4">{children}</div></section>

export default function Partograph({f,patch,save}){
 const labor=f.sections.labor||{}, observations=Array.isArray(labor.observations)?labor.observations:[]
 const[o,setO]=useState(fresh),[editing,setEditing]=useState(observations.length?observations.length-1:null),[message,setMessage]=useState(''),[now,setNow]=useState(clock()),[activeGroup,setActiveGroup]=useState('fetal')
 useEffect(()=>{const timer=setInterval(()=>setNow(clock()),1000);return()=>clearInterval(timer)},[])
 const update=e=>setO(x=>({...x,[e.target.name]:e.target.value})),header=(key,value)=>patch('labor',key,value)
 const today=new Date().toISOString().slice(0,10), admissionDate=labor.admission_date||today, admissionTime=labor.admission_time||clock()
 const elapsed=()=>{const start=new Date(`${admissionDate}T${admissionTime}`),seen=new Date(`${admissionDate}T${o.time}`);if(seen<start)seen.setDate(seen.getDate()+1);return Math.max(0,(seen-start)/3600000).toFixed(1)}
 const persist=async next=>{const nextLabor={...labor,admission_date:admissionDate,admission_time:admissionTime,observations:next};patch('labor','admission_date',admissionDate);patch('labor','admission_time',admissionTime);patch('labor','observations',next);await save({...f,sections:{...f.sections,labor:nextLabor}})}
 const add=async()=>{if(editing===null&&observations.length){setMessage('Select an existing observation below to edit it.');return}if(!o.time){setMessage('Enter the observation time.');return}const entry={...o,hour:o.hour||elapsed()},next=[...observations];editing===null?next.push(entry):next.splice(editing,1,entry);next.sort((a,b)=>(a.time||'').localeCompare(b.time||''));await persist(next);const savedIndex=next.findIndex(x=>x.time===entry.time);setO(entry);setEditing(savedIndex);setMessage('Observation updated and saved.')}
 const edit=index=>{setO(observations[index]);setEditing(index);document.querySelector('.partograph-entry')?.scrollIntoView({behavior:'smooth'})}
 const remove=async index=>{await persist(observations.filter((_,i)=>i!==index));setMessage('Observation removed and record updated.')}
 const groups=[
  ['time','Time column',<><Field label="Time" type="time" name="time" value={o.time} onChange={update}/><Field label="Hours since admission" type="number" step="0.5" name="hour" value={o.hour} onChange={update}/></>],
  ['fetal','Fetal condition',<><Field label="Fetal heart rate (bpm)" type="number" min="80" max="200" name="fhr" value={o.fhr} onChange={update}/><Field label="Amniotic fluid" name="amniotic_fluid" placeholder="I / C / M / B" value={o.amniotic_fluid} onChange={update}/><Field label="Moulding" name="moulding" placeholder="0 / + / ++ / +++" value={o.moulding} onChange={update}/></>],
  ['progress','Labor progress',<><Field label="Cervix (cm) - plot X" type="number" min="0" max="10" step="0.5" name="cervix" value={o.cervix} onChange={update}/><Field label="Descent of head - plot O" type="number" min="0" max="5" name="descent" value={o.descent} onChange={update}/><Field label="Contractions per 10 minutes" type="number" min="0" max="5" name="contractions" value={o.contractions} onChange={update}/><Field label="Contraction duration (seconds)" type="number" name="contraction_duration" value={o.contraction_duration} onChange={update}/></>],
  ['treatment','Oxytocin and fluids',<><Field label="Oxytocin U/L" name="oxytocin_ul" value={o.oxytocin_ul} onChange={update}/><Field label="Drops/min" type="number" name="drops_min" value={o.drops_min} onChange={update}/><Field label="Drugs given and IV fluids" name="drugs_fluids" value={o.drugs_fluids} onChange={update}/></>],
  ['maternal','Maternal condition',<><Field label="Pulse (bpm)" type="number" name="pulse" value={o.pulse} onChange={update}/><Field label="Systolic BP" type="number" name="systolic" value={o.systolic} onChange={update}/><Field label="Diastolic BP" type="number" name="diastolic" value={o.diastolic} onChange={update}/><Field label="Temperature C" type="number" step="0.1" name="temperature" value={o.temperature} onChange={update}/></>],
  ['urine','Urine',<><Field label="Protein" name="urine_protein" value={o.urine_protein} onChange={update}/><Field label="Acetone" name="urine_acetone" value={o.urine_acetone} onChange={update}/><Field label="Volume (mL)" type="number" name="urine_volume" value={o.urine_volume} onChange={update}/></>]
 ]
 const active=groups.find(([id])=>id===activeGroup)||groups[0],filled=Object.values(o).filter(v=>String(v||'').trim()).length
 return <section className="panel form-card partograph"><div className="panel-heading"><div><p className="eyebrow">PAGE 3 · INTRAPARTUM CARE</p><h3>Monitoring progress of labor using partograph</h3><p className="helper">Add one time-based observation for every monitoring column in the paper chart.</p></div><span className="tag">{observations.length} observations</span></div>
  <div className="partograph-clock"><span className="online-dot"/><b>Live observation clock: {now}</b><small>Elapsed hours are calculated from admission automatically.</small></div><div className="labor-summary"><article><span>Admission</span><b>{admissionDate}</b><small>{admissionTime}</small></article><article><span>Latest FHR</span><b>{observations.at(-1)?.fhr||'-'}</b><small>bpm</small></article><article><span>Cervix</span><b>{observations.at(-1)?.cervix||'-'}</b><small>cm latest</small></article><article><span>Current entry</span><b>{filled}</b><small>fields filled</small></article></div><div className="form-grid cols-4 compact-grid"><Field label="Date of admission" type="date" value={admissionDate} onChange={e=>header('admission_date',e.target.value)}/><Field label="Time of admission" type="time" value={admissionTime} onChange={e=>header('admission_time',e.target.value)}/><Field label="Ruptured membranes" placeholder="Time / status" value={labor.ruptured_membranes||''} onChange={e=>header('ruptured_membranes',e.target.value)}/><Field label="Hours ruptured" type="number" value={labor.ruptured_hours||''} onChange={e=>header('ruptured_hours',e.target.value)}/></div>
  <div className="partograph-charts"><Chart title="Fetal heart rate" data={observations} lines={[['fhr','#157078',80,200]]}/><Chart title="Cervix and head descent" data={observations} lines={[['cervix','#c34f4f',0,10],['descent','#276aa5',0,10]]}/><Chart title="Pulse and blood pressure" data={observations} lines={[['pulse','#7547a8',60,180],['systolic','#c34f4f',60,180],['diastolic','#276aa5',60,180]]}/></div>
  <div className="partograph-entry"><div className="active-contact-head"><div><p className="eyebrow">{editing===null?'NEW OBSERVATION':'EDIT OBSERVATION'}</p><h3>{editing===null?'Record monitoring values':`Observation ${editing+1}`}</h3></div>{message&&<span>{message}</span>}</div>
   <div className="compact-stepper">{groups.map(([id,title])=><button key={id} className={activeGroup===id?'active':''} onClick={()=>setActiveGroup(id)}><span>{title}</span></button>)}</div>
   <Group title={active[1]}>{active[2]}</Group>
   <div className="partograph-actions"><button className="secondary" onClick={add}>{editing===null?(observations.length?'Select observation to edit':'Save first observation'):'Update and save observation'}</button>{editing!==null&&observations.length>1&&<button className="link" onClick={()=>{setEditing(null);setO(fresh())}}>Cancel edit</button>}</div>
  </div>
  <div className="table-scroll partograph-history"><table><thead><tr><th>Time</th><th>Fetal condition</th><th>Labor progress</th><th>Contractions</th><th>Oxytocin</th><th>Maternal condition</th><th>Urine</th><th></th></tr></thead><tbody>{observations.length?observations.map((x,i)=><tr key={i}><td><b>{x.time}</b><small>{x.hour||'-'} hours</small></td><td>{x.fhr||'-'} bpm<small>{x.amniotic_fluid||'-'} · {x.moulding||'-'}</small></td><td>{x.cervix||'-'} cm<small>Descent {x.descent||'-'}</small></td><td>{x.contractions||'-'} / 10 min<small>{x.contraction_duration||'-'} sec</small></td><td>{x.oxytocin_ul||'-'}<small>{x.drops_min||'-'} drops/min</small></td><td>{x.pulse||'-'} · {x.systolic||'-'}/{x.diastolic||'-'}<small>{x.temperature||'-'} °C</small></td><td>{x.urine_volume||'-'} mL<small>P {x.urine_protein||'-'} · A {x.urine_acetone||'-'}</small></td><td><button className="link" onClick={()=>edit(i)}>Edit</button><button className="link danger-link" onClick={()=>remove(i)}>Remove</button></td></tr>):<tr><td colSpan="8" className="empty-table">No labor observations recorded.</td></tr>}</tbody></table></div>
  <p className="helper">Every added, edited or removed observation is saved immediately. The full-save button remains available for admission details changed without adding an observation.</p><button className="primary" onClick={save}>Save admission details</button>
 </section>
}

function Chart({title,data,lines}){const w=520,h=170,p=28;const points=(key,min,max)=>data.map((d,i)=>{if(d[key]===''||!Number.isFinite(+d[key]))return null;const x=p+(i/Math.max(1,data.length-1))*(w-p*2),y=h-p-((+d[key]-min)/(max-min))*(h-p*2);return `${x},${Math.max(p,Math.min(h-p,y))}`}).filter(Boolean).join(' ');return <article><b>{title}</b><svg viewBox={`0 0 ${w} ${h}`}>{[0,1,2,3,4,5].map(i=><line key={i} x1={p} x2={w-p} y1={p+i*(h-p*2)/5} y2={p+i*(h-p*2)/5}/>)}{data.map((_,i)=><line key={'v'+i} y1={p} y2={h-p} x1={p+(i/Math.max(1,data.length-1))*(w-p*2)} x2={p+(i/Math.max(1,data.length-1))*(w-p*2)}/>)}{lines.map(([key,color,min,max])=><polyline key={key} points={points(key,min,max)} fill="none" stroke={color} strokeWidth="3"/>)}</svg><div className="chart-legend">{lines.map(([key,color])=><span key={key}><i style={{background:color}}/>{key.replace('_',' ')}</span>)}</div></article>}
